using System;
using System.Web.UI;

namespace TradeCompany
{
    public partial class ShowInfo : Page
    {
        protected void Add_Order_Btn_Click(object sender, EventArgs e)
        {
            Add_Order_Pnl.Visible = true;
        }

        protected void Add_Btn_Click(object sender, EventArgs e)
        {
            TradeCompanyDataSource2.Insert();
            CustomerOrdersGridView.DataBind();
            CleanAddOrdersTextboxes();           
        }

        private void CleanAddOrdersTextboxes()
        {
            Order_Name.Text = string.Empty;
            Order_Price.Text = string.Empty;
            Order_Count.Text = string.Empty;
            Add_Order_Pnl.Visible = false;
        }

        protected void Clean_Btn_Click(object sender, EventArgs e)
        {
            CleanAddOrdersTextboxes();
        }

        protected void Update_Order_Btn_Click(object sender, EventArgs e)
        {
            if (Update_Order_Btn.Text == "Редактировать заказы")
            {
                CustomerOrdersGridView.AutoGenerateEditButton = true;
                Update_Order_Btn.Text = "Закончить редактирование";
            }
            else
            {
                CustomerOrdersGridView.AutoGenerateEditButton = false;
                Update_Order_Btn.Text = "Редактировать заказы";
            }
        }

        protected void Delete_Order_Btn_Click(object sender, EventArgs e)
        {
            if (Delete_Order_Btn.Text == "Удалить заказ")
            {
                CustomerOrdersGridView.AutoGenerateDeleteButton = true;
                Delete_Order_Btn.Text = "Закончить удаление";
            }
            else
            {
                CustomerOrdersGridView.AutoGenerateDeleteButton = false;
                Delete_Order_Btn.Text = "Удалить заказ";
            }
        }
    }
}