using System;
using System.Web.UI;

namespace TradeCompany
{
    public partial class ShowInfo : Page
    {
        protected void Add_Order_Btn_Click(object sender, EventArgs e)
        {
            Add_Order_Pnl.Visible = true;
        }

        protected void Add_Order_Pnl_Btn_Click(object sender, EventArgs e)
        {
            TradeCompanyDataSource2.Insert();
            CustomerOrdersGridView.DataBind();
            CleanAddOrdersTextboxes();           
        }

        private void CleanAddOrdersTextboxes()
        {
            Order_Name.Text = string.Empty;
            Order_Price.Text = string.Empty;
            Order_Count.Text = string.Empty;
            Add_Order_Pnl.Visible = false;
        }

        protected void Clean_Order_Btn_Click(object sender, EventArgs e)
        {
            CleanAddOrdersTextboxes();
        }

        protected void Update_Order_Btn_Click(object sender, EventArgs e)
        {
            if (Update_Order_Btn.Text == "Редактировать заказы")
            {
                CustomerOrdersGridView.AutoGenerateEditButton = true;
                Update_Order_Btn.Text = "Закончить редактирование";
            }
            else
            {
                CustomerOrdersGridView.AutoGenerateEditButton = false;
                Update_Order_Btn.Text = "Редактировать заказы";
            }
        }

        protected void Delete_Order_Btn_Click(object sender, EventArgs e)
        {
            if (Delete_Order_Btn.Text == "Удалить заказ")
            {
                CustomerOrdersGridView.AutoGenerateDeleteButton = true;
                Delete_Order_Btn.Text = "Закончить удаление";
            }
            else
            {
                CustomerOrdersGridView.AutoGenerateDeleteButton = false;
                Delete_Order_Btn.Text = "Удалить заказ";
            }
        }

        protected void Add_Customer_Btn_Click(object sender, EventArgs e)
        {
            Add_Customer_Pnl.Visible = true;
        }

        private void CleanAddCustomerTextboxes()
        {
            Customer_Name.Text = string.Empty;
            Customer_Surname.Text = string.Empty;
            Customer_YearOfBirth.Text = string.Empty;
            Add_Customer_Pnl.Visible = false;
        }

        protected void Clean_Customer_Btn_Click(object sender, EventArgs e)
        {
            CleanAddCustomerTextboxes();
        }

        protected void Add_Customer_Pnl_Btn_Click(object sender, EventArgs e)
        {
            TradeCompanyDataSource.Insert();
            CustomersGridView.DataBind();
            CleanAddCustomerTextboxes();
        }

        protected void Update_Customer_Btn_Click(object sender, EventArgs e)
        {
            if (Update_Customer_Btn.Text == "Редактировать покупателей")
            {
                CustomersGridView.AutoGenerateEditButton = true;
                Update_Customer_Btn.Text = "Закончить редактирование";
            }
            else
            {
                CustomersGridView.AutoGenerateEditButton = false;
                Update_Customer_Btn.Text = "Редактировать покупателей";
            }
        }

        protected void Delete_Customer_Btn_Click(object sender, EventArgs e)
        {
            if (Delete_Customer_Btn.Text == "Удалить покупателя")
            {
                CustomersGridView.AutoGenerateDeleteButton = true;
                Delete_Customer_Btn.Text = "Закончить удаление";
            }
            else
            {
                CustomersGridView.AutoGenerateDeleteButton = false;
                Delete_Customer_Btn.Text = "Удалить покупателя";
            }
        }
    }
}